/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        outline: "#74777f",
        "on-tertiary-container": "#b5785f",
        "on-secondary-fixed": "#131c29",
        "on-primary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "primary-container": "#001f3f",
        "tertiary-fixed": "#ffdbce",
        tertiary: "#110200",
        "on-secondary-fixed-variant": "#3e4756",
        "inverse-surface": "#2e3132",
        background: "#f8f9fa",
        "outline-variant": "#c4c6cf",
        "surface-dim": "#d9dadb",
        "secondary-container": "#d7e0f2",
        "primary-fixed-dim": "#afc8f0",
        "secondary-fixed-dim": "#bec7d9",
        "error-container": "#ffdad6",
        "surface-tint": "#476083",
        "surface-container-high": "#e7e8e9",
        error: "#ba1a1a",
        surface: "#f8f9fa",
        "primary-fixed": "#d4e3ff",
        "on-surface-variant": "#43474e",
        "on-primary-fixed": "#001c3a",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#2f486a",
        "on-error-container": "#93000a",
        "on-background": "#191c1d",
        "on-surface": "#191c1d",
        "on-error": "#ffffff",
        "inverse-primary": "#afc8f0",
        primary: "#000613",
        "surface-bright": "#f8f9fa",
        secondary: "#565f6e",
        "on-tertiary-fixed-variant": "#6b3a25",
        "on-primary-container": "#6f88ad",
        "surface-container": "#edeeef",
        "on-secondary-container": "#5a6372",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-fixed-dim": "#fdb69a",
        "tertiary-container": "#391303",
        "secondary-fixed": "#dae3f5",
        "on-tertiary-fixed": "#351002",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      animation: {
        "ticker-scroll": "ticker-scroll 35s linear infinite",
        "pulse-slow": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in": "fadeIn 0.6s ease-out",
      },
      keyframes: {
        "ticker-scroll": {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};
